"""initial schema

Revision ID: cdedde6f8abd
Revises: 
Create Date: 2026-04-17 09:42:59.821182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_indices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('prev_close', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_market_index_symbol_date')
    )
    with op.batch_alter_table('market_indices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_indices_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_indices_symbol'), ['symbol'], unique=False)

    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_ticker'), ['ticker'], unique=True)

    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_logs_created_at'), ['created_at'], unique=False)

    op.create_table('daily_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uq_daily_bar_stock_date')
    )
    with op.batch_alter_table('daily_bars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_bars_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_bars_stock_id'), ['stock_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('position_size', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_stock_id'), ['stock_id'], unique=False)

    op.create_table('pullbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('ma150_value', sa.Float(), nullable=False),
    sa.Column('distance_pct', sa.Float(), nullable=False),
    sa.Column('return_10d', sa.Float(), nullable=True),
    sa.Column('return_20d', sa.Float(), nullable=True),
    sa.Column('return_30d', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uq_pullback_stock_date')
    )
    with op.batch_alter_table('pullbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pullbacks_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pullbacks_stock_id'), ['stock_id'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('ma150_value', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('distance_pct', sa.Float(), nullable=True),
    sa.Column('slope_positive', sa.Boolean(), nullable=True),
    sa.Column('slope_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uq_signal_stock_date')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_stock_id'), ['stock_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_stock_id'))
        batch_op.drop_index(batch_op.f('ix_signals_date'))

    op.drop_table('signals')
    with op.batch_alter_table('pullbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pullbacks_stock_id'))
        batch_op.drop_index(batch_op.f('ix_pullbacks_date'))

    op.drop_table('pullbacks')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_stock_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_date'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('daily_bars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_bars_stock_id'))
        batch_op.drop_index(batch_op.f('ix_daily_bars_date'))

    op.drop_table('daily_bars')
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_logs_created_at'))

    op.drop_table('system_logs')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_ticker'))

    op.drop_table('stocks')
    with op.batch_alter_table('market_indices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_indices_symbol'))
        batch_op.drop_index(batch_op.f('ix_market_indices_date'))

    op.drop_table('market_indices')
    # ### end Alembic commands ###
